import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Circle",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className="dark">
      <body
        className={
          inter.className +
          "max-w-screen-2xl mx-auto min-h-screen flex flex-col antialiased bg-white dark:bg-slate-950 items-center"
        }
      >
        <div className="flex-1 flex flex-col container bg-slate-50 dark:bg-slate-900/30 text-black dark:text-slate-200 border-x border-slate-200 dark:border-slate-700/50">
          <Header />
          <div className="flex-1">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
